version: '3'


services:
  auth-microservice:
    image: auth-microservice:1.0
    build:
      context: /auth-microservice
      dockerfile: Dockerfile
    container_name: auth-microservice
    depends_on:
      - postgres-auth-db
    ports:
      - '8080:8080'
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auth-db:5432/postgres-auth-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234




  postgres-auth-db:
    image: postgres:15.1-alpine
    container_name: postgres-auth-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres-auth-db
    ports:
      - '5433:5432'




  order-microservice:
    image: order-microservice:1.0
    build:
      context: /order-microservice
      dockerfile: Dockerfile
    container_name: order-microservice
    depends_on:
      - auth-microservice
      - postgres-order-db
    ports:
      - '9090:9090'
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-order-db:5432/postgres-order-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234



  postgres-order-db:
    image: postgres:15.1-alpine
    container_name: postgres-order-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres-order-db
    ports:
      - '5434:5432'