server:
  port: 8080


app:
  jwt:
    secret: "am52cm52Z25pYWVyamlndmppZmp0bmh1YXJqaW92bnVlZml2bnJzZXViYWlmaml0"
    lifetime: 15m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres-auth-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true