server:
  port: 9090

auth:
  details:
    address: "http://auth-microservice:8080/auth-microservice/v1/auth"


spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres-order-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  task:
    scheduling:
      pool:
        size: 2
  flyway:
    baseline-on-migrate: true
